repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black .
        language: system
        types: [python]
