name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: x64
    - run: pip install poetry==1.0.5
    - run: pip install poetry-dynamic-versioning
    - run: poetry install
    - run: poetry run mypy .
    - run: poetry run pytest --cov=streamstate_utils --cov-report=xml
    - uses: codecov/codecov-action@v1
      with:
        #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./coverage.xml # optional
        fail_ci_if_error: false # optional (default = false)
        verbose: true # optional (default = false)
